### ISSUE TITLE
Update terraform readme

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial#102]
1. update https://github.com/systemaccounting/mxfactorial/blob/master/terraform/README.md
1. new engineers executes steps

*expected*
new env created by new engineer with few questions

**Comment by mxfactorial** [comment]
@ryancheta please add hourly estimate

**Comment by ryancheta** [comment]
Estimate of total time spent to complete: 3 hours

**Comment by mxfactorial** [comment]
Approved, from develop please
