### ISSUE TITLE
add notification feature in react client

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial#115]
*test case titles = expected*

[websocket client integration instructions](https://github.com/systemaccounting/mxfactorial/blob/0e6237fd53fa072876e8d08d8ae868bed910c2bf/services/notification/README.md) and [minimal example](https://github.com/systemaccounting/mxfactorial/tree/master/services/notification/wss-client-instructions) available in `services/notification`

---

**notification assets detected by [e2e inventory test](https://github.com/systemaccounting/mxfactorial/blob/0e6237fd53fa072876e8d08d8ae868bed910c2bf/react/e2e/private/homeScreen/homeScreenInventory.test.js)**

from [buyerApproveRequestSequence](https://docs.google.com/drawings/d/1cF2Ai_lmOaXXI8Z2hso7tbWoNouYNgJ9eFCQES0rPcU/edit?usp=sharing)
1. add [notificationFlag](https://drive.google.com/file/d/1hhDzvvu9ofrgNh5T6UfneTA-flJdmPYQ/view?usp=sharing)
1. add notificationCounter
1. add notificationDropDownMenu
1. add notificationDropDownMenuItem
1. add clearAllButton

---

**notificationDropDownMenu displays with clearAllButton, and 1 notificationDropDownMenuItem displays with grayed out, italicized "none" content**

1. sign in TestAccount with 0 pending notifications
1. sign in TestAccount
1. select notificationFlag

---

**notificationDropDownMenu dismissed**

1. sign in TestAccount
1. select notificationFlag to display notificationDropDownMenu
1. select elsewhere to onblur

---

**websocket connection created**

1. sign in TestAccount
1. post-auth component sends websocket authentication and connection request

---

**pending notifications received in state**

1. TestAccountA sends transaction request to TestAccountB
1. sign in TestAccountB
1. post-auth component sends `getnotifications` action to websocket server

---

**notificationCounter increased by 1**

1. receive 1 pending notification

---

**notificationDropDownMenuItem displayed request time, requesting account with magnitude and direction of transaction**

1. receive pending notification
1. select notificationFlag

---

**notificationDropDownMenuItems sequenced in descending request time**

1. receive multiple pending notifications

---

**pending notifications cleared from state**

1. receive pending notification
1. select clearAllButton
1. post-auth component sends `clearnotifications` action with notifications to websocket server

---

**notificationCounter decreases by 1**

1. receive 1 pending notification
1. select clearAllButton

---

**notificationDropDownMenu dismissed**

1. receive 1 pending notification
1. select clearAllButton

---

**estimations will include unit and e2e test coverage of requirements. new screens will include an e2e inventory test ([example](https://github.com/systemaccounting/mxfactorial/blob/cec04261f6e3e47356b2f0338f851bd71e2f59bc/react/e2e/private/homeScreen/homeScreenInventory.test.js))*

**Comment by oozywaters** [comment]
1. Notification counter + dropdown menu + e2e inventory test - 3h
2. Empty notification item + test - 1h
3. Dropdown menu is dismissing correctly test - 1h
4. Add websocket connection to post-auth component + test - 2h
5. Notifications are being received and persisted in state + test - 3h
6. Notification item displays required info and in right order + test - 2h
7. Clear notifications, decreasing notifications counter + test - 1h
Total: **13h**

**Comment by mxfactorial** [comment]
approved, from develop please

**Comment by mxfactorial** [comment]
please add estimation:

let `n` = pending notifications stored in client state

1. sign in to display homeScreen
1. client requests `20 - n` pending notifications as [number value](https://github.com/systemaccounting/mxfactorial/blob/9c5efcbb4ca31e65de4b11db2f9b746a8028a8bd/services/notification/notification-get-faas/tests/sort.integ.js#L102-L105) to new `count` property in `getnotifications` websocket message

**expected**
`20 - n` pending notifications received

**Comment by oozywaters** [comment]
Additional estimation: **2h**

**Comment by mxfactorial** [comment]
approved

**Comment by oozywaters** [comment]
Fix blinking notifications counter: **2h**

**Comment by mxfactorial** [comment]
approved

**Comment by mxfactorial** [comment]
please add estimation:

**time to set notificationCounter to 0 < 10 ms** or *lowest possible with react*

1. receive 1 pending notification
1. select clearAllButton

**Comment by mxfactorial** [comment]
closed by https://github.com/systemaccounting/mxfactorial/pull/122
