### ISSUE TITLE
remove const assignments from env vars for convenient testing

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial#124]
example: [notification-clear-faas/index.js](https://github.com/systemaccounting/mxfactorial/blob/3ef44add0ddfc40c47f210a5e5985e2ed9622400/services/notification/notification-clear-faas/index.js)

please audit files, inventory here and remove const assignments @chrishernandezmagcamit

**Comment by ctophermags** [comment]
closed by https://github.com/systemaccounting/mxfactorial/pull/125
