### ISSUE TITLE
created_at timestamps missing from websocket connection_id records in dynamodb

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial#146]
1. create websocket to include [connectedAt](https://github.com/systemaccounting/mxfactorial/blob/875a007355a74c19f6496a395418a93ba3c48f3a/services/notification/wss-notif-connect-faas/index.js#L22) api gateway timestamp in new `connection_id` dynamodb record

**observed**

`created_at` timestamp missing  

<img width="272" alt="missing-timestamp" src="https://user-images.githubusercontent.com/12200465/69921358-d100a200-1445-11ea-8b76-84dc5e648a55.png">

**Comment by mxfactorial** [comment]
reproduced missing timestamp in dynamodb connection_id records with react `yarn test:e2e-private` on [client-notifications](https://github.com/systemaccounting/mxfactorial/pull/122) branch

**Comment by ctophermags** [comment]
closed by https://github.com/systemaccounting/mxfactorial/pull/155
