### ISSUE TITLE
fix react unit test warnings

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial#165]
1. `cd react`
1. `yarn test`

**observed**

```js
Warning: componentWillMount has been renamed...
Warning: componentWillReceiveProps has been renamed...
(node:66701) UnhandledPromiseRejectionWarning: Error: expect(jest.fn()).toHaveBeenCalled()...
```

**expected**
0 warnings

**Comment by oozywaters** [comment]
1. Fix RequestDetailScreen prop types warning
2. Fix ApprovalModal.test.js unhandled promise rejection error
3. Fix deprecated lifecycle methods warnings

**Estimate: 1h**

**Comment by mxfactorial** [comment]
approved

**Comment by mxfactorial** [comment]
closed by https://github.com/systemaccounting/mxfactorial/pull/186
