### ISSUE TITLE
requestScreen and requestDetailScreen display query values

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial#172]
*test case titles = expected*

from [buyerApproveRequestSequence](https://docs.google.com/drawings/d/1cF2Ai_lmOaXXI8Z2hso7tbWoNouYNgJ9eFCQES0rPcU/edit?usp=sharing)

historical
1. https://github.com/systemaccounting/mxfactorial/issues/68
1. https://github.com/systemaccounting/mxfactorial/issues/98

---

**requestScreen displays 20 most recent requestItemIndicator in descending time**

1. add "requests" [query and mutation](https://github.com/systemaccounting/mxfactorial/tree/26ae4f17d16b250663edde14c5dcf31cc38a1cd9/react/src/queries)
1. remove [transaction mutation](https://github.com/systemaccounting/mxfactorial/blob/develop/react/src/queries/transactions.js#L3-L15)
1. select mainNavRequestButton
1. send graphql [requests](https://github.com/systemaccounting/mxfactorial/issues/170) query

---

**requestDetailScreen displays debit request values fetched from graphql request query**

1. account A requests debit from account B
1. account B selects mainNavButton to display mainNavMenu
1. account B selects mainNavRequestButton to navigate to requestScreen
1. account B selects requestItemIndicator

---

**requestDetailScreen displays credit request values fetched from graphql request query**

1. account A requests credit from account B
1. account B selects mainNavButton to display mainNavMenu
1. account B selects mainNavRequestButton to navigate to requestScreen
1. account B selects requestItemIndicator

---

**estimations will include unit and e2e test coverage of requirements. new screens will include an e2e inventory test ([example](https://github.com/systemaccounting/mxfactorial/blob/cec04261f6e3e47356b2f0338f851bd71e2f59bc/react/e2e/private/homeScreen/homeScreenInventory.test.js))*

```diff
- add estimation for thorough e2e testing
```

**Comment by oozywaters** [comment]
1. Add requests query and mutation, remove transaction mutation - 1h
2. Display 20 most recent requests received from new requests query + fix e2e tests - 3h
3. Display debit request details + e2e - 3h
4.  Display credit request details + e2e - 3h
Total: **10h**

**Comment by mxfactorial** [comment]
approved, from `requests` branch please

**Comment by mxfactorial** [comment]
closed by https://github.com/systemaccounting/mxfactorial/pull/179
