### ISSUE TITLE
historyScreen and historyDetailScreen display query values

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial#173]
*test case titles = expected*

from [historyDetailScreenSequence](https://docs.google.com/drawings/d/1W4KTDjrqXGz7Xvv56529XBKnOoDdwBZzqUyHPuYQGbE/edit?usp=sharing)

historical
1. https://github.com/systemaccounting/mxfactorial/issues/69

dependencies
1. https://github.com/systemaccounting/mxfactorial/issues/171

---

**debitor_approval_time added to debit request record**

1. receive debit request
1. select mainNavButton to display mainNavMenu
1. select mainNavRequestButton to navigate to requestScreen
1. select requestItemIndicator to navigate to requestDetailScreen
1. select transactButton on requestDetailScreen to display passwordApproveTransactionPopup
1. add password to passwordInputField on passwordApproveTransactionPopup
1. select okButton on passwordApproveTransactionPopup
1. send graphql requests mutation
1. receive 200 with transaction
1. display historyScreen with newly-fetched transactions from graphql query
1. transactionSuccessPopup displays 

---

**creditor_approval_time added to credit request record**

1. receive credit request
1. select mainNavButton to display mainNavMenu
1. select mainNavRequestButton to navigate to requestScreen
1. select requestItemIndicator to navigate to requestDetailScreen
1. select transactButton on requestDetailScreen to display passwordApproveTransactionPopup
1. add password to passwordInputField on passwordApproveTransactionPopup
1. select okButton on passwordApproveTransactionPopup
1. send graphql requests mutation
1. receive 200 with transaction
1. display historyScreen with newly-fetched transactions from graphql query
1. transactionSuccessPopup displays 

---

**credit request transactionSuccessPopup**

1. receive credit request
1. approve from passwordApproveTransactionPopup

---

**debit request transactionSuccessPopup**

1. receive debit request
1. approve from passwordApproveTransactionPopup

---

**debitor_approval_time NOT added after failed password**

1. receive debit request
1. add failing password to passwordInputField on passwordApproveTransactionPopup
1. select okButton on passwordApproveTransactionPopup

---

**creditor_approval_time NOT added after failed password**

1. receive credit request
1. add failing password to passwordInputField on passwordApproveTransactionPopup
1. select okButton on passwordApproveTransactionPopup

---

**dismiss transactionSuccessPopup**

1. approve from passwordApproveTransactionPopup to display okButton on transactionSuccessPopup
1. select okButton

---

**historyScreen displays 20 most recent historyItemIndicator in descending time**

1. select mainNavHistoryButton
1. send graphql [transactions](https://github.com/systemaccounting/mxfactorial/issues/170) query

---

**historyDetailScreen displays credit transaction values fetched from graphql transactions query**

1. account A requests credit from account B
1. account B approves credit request from account A
1. account B auto-navigates to historyScreen
1. account B selects historyItemIndicator of new transaction

---

**historyDetailScreen displays debit transaction values fetched from graphql transactions query**

1. account A requests debit from account B
1. account B approves debit request from account A
1. account B auto-navigates to historyScreen
1. account B selects historyItemIndicator of new transaction

---

**estimations will include unit and e2e test coverage of requirements. new screens will include an e2e inventory test ([example](https://github.com/systemaccounting/mxfactorial/blob/cec04261f6e3e47356b2f0338f851bd71e2f59bc/react/e2e/private/homeScreen/homeScreenInventory.test.js))*

```diff
- add estimation for thorough e2e testing
```

**Comment by oozywaters** [comment]
1. Send new debit/credit requests mutation on transact button click + e2e fix - 3h
2. Display requests on historyScreen received from new requests query + e2e - 3h
3. Approve from transactionSuccessPopup - 2h
4. Failed password flow - 2h
5. Approve credit/debit requests on historyDetailsScreen flow + e2e - 3h
Total: **13h**

**Comment by mxfactorial** [comment]
approved

**Comment by mxfactorial** [comment]
closed by https://github.com/systemaccounting/mxfactorial/pull/181
