### ISSUE TITLE
AuthForm and AddTransactionForm improvements

### ISSUE THREAD

**Issue by oozywaters** [systemaccounting/mxfactorial#187]
Refactor authentication and add transaction forms, get rid of state management logic inside components, improve stability and maintainability using declarative approach.

Possible solutions:
- [redux-form](https://github.com/redux-form/redux-form)
- [final-form](https://github.com/final-form/final-form)

**Comment by oozywaters** [comment]
Estimate:
1. AuthForm - 6h
2. AddTransactionForm - 12h
Total: **18h**

**Comment by mxfactorial** [comment]
approved

**Comment by oozywaters** [comment]
Closed by  #188
