### ISSUE TITLE
add unit and integration test coverage to query request by id service

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial#190]
1.  add unit test coverage to [services/req-query-trans-id-faas](https://github.com/systemaccounting/mxfactorial/blob/02e2c3f5d32c26ab8710ea3cd0772e09497eae55/services/req-query-trans-id-faas/main.go)
1. `go test -cover`

**expected**
majority coverage

---

1. add integration test coverage to services/req-query-trans-id-faas
1. insert transaction record with all values assigned into postgres db
1. invoke lambda with transaction id
 
**expected**
lambda returns request record with assigned values

**Comment by cicika** [comment]
1. Refactor to make code testable 
2. Create test data for unit tests with SQLite
3. Create integration test with test PG instance (can reuse from previous point)
4. Update CI files to run new tests

I will overshoot with the estimate, just in case :) 
**Estimate: 3h**
**Delivery: Fri, May 22nd**

**Comment by mxfactorial** [comment]
approved, from develop please

**Comment by mxfactorial** [comment]
> Delivery: Fri, May 22nd

intended?

**Comment by cicika** [comment]
It was. Got slightly stuck running integration test locally, will update soon.

**Comment by mxfactorial** [comment]
filling holes in process script. new version:

```
1. requirements added as github issues by maintainer
2. maintainer solicits estimation from developer
3. developer issues delivery date and itemized hourly estimation budgeting for i) feature addition or fix, ii) unit tests, iii) integration tests, iv) code review and v) code review changes
4. maintainer approves estimation from developer
5. developer branches and creates wip pull request
6. developer proposes new delivery date and itemized hourly estimation of obstacles posing risk to initially negotiated estimation
7. maintainer eliminates obstacles posing risk to initially negotiated estimation
8. maintainer accepts or rejects new estimation
9. developer finishes pull request
10. unless negotiated, developer maintains or increases code coverage
11. developer requests code review from maintainer
12. developer adds changes required during code review
13. all tests pass before or on accepted delivery date
14. maintainer merges pull request
15. maintainer pays developer
```

please comment approval or rejection in billing tool

if rejecting, please close wip pull request
else, begin from #6 by posting comment here

process script aims to protect maintainer from management costs
