### ISSUE TITLE
Add a /transact REST endpoint

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial#25]
Add a /transact REST endpoint to receive & persist transaction data POSTed by clients (e.g. https://docs.google.com/drawings/d/1nt4Kohxm-Gogw7rK_h_dH6Bl8cLmHOUuFpTtJdB0KZk/edit).

Be familiar with 
i) https://cloud.google.com/datastore/docs/concepts/overview#comparison_with_traditional_databases 
ii) https://cloud.google.com/nodejs/getting-started/using-cloud-datastore,and 
iii) https://cloud.google.com/datastore/docs/concepts/entities

Requirements:
a. app.use your CRUD operation in main.js when a request for /systemaccounting/transact is received, similar to https://github.com/systemaccounting/mxfactorial/blob/master/main.js#L34
b. Add /transact/crud.js, similar to https://github.com/systemaccounting/mxfactorial/tree/master/users 
c. Transaction objects received from POST requests will be divided into 4 object ‘kinds’ (https://cloud.google.com/datastore/docs/concepts/entities#ancestor_paths) by the time they reach the Datastore where they will form an ancestor/child relationship defined as an ‘entity group’ (“When you create an entity, you can optionally designate another entity as its parent; the new entity is a child of the parent entity..." - https://cloud.google.com/datastore/docs/concepts/entities#properties_and_value_types).

The first object, or “root” & “sole parent” of this entity group is of the ‘transaction’ kind:

(keys for these entities will be numeric IDs automatically assigned by the Datastore*)
db_author
cr_author
rejection_time
expiration_time

The second object, or child of this entity group is of the ‘debitor’ kind:

db_time
db_latlng

The third object, or child of this entity group is of the ‘creditor’ kind:

cr_time
cr_latlng

The fourth object, or child of this entity group is of the ‘transaction_item’ kind:

db_account
cr_account
value
quantity
units_measured
unit_of_measurement
name

d. Creating a transaction entity requires transaction_item entity > 0.
e. Leave Request & Response as a comment in this issue for client engineers.

Type checking will be added later: https://cloud.google.com/datastore/docs/concepts/entities#properties_and_value_types 

*Note: Entities are assigned random numeric IDs by the Datastore per https://cloud.google.com/datastore/docs/concepts/entities#ancestor_paths. Alternatively, there is the option to assign property values to serve as keys (e.g., ‘username’ will be the key; not some number generated by the Datastore).

How to configure your environment & deliver code: https://github.com/systemaccounting/mxfactorial/wiki/Code-Delivery-Workflow

**Comment by ghost** [comment]
@mxfactorial  Please see PR #34

**Comment by mxfactorial** [comment]
Closed by https://github.com/systemaccounting/mxfactorial/pull/34
