### ISSUE TITLE
Refine the user data model

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial#26]
Summary: Every time an account is created, two objects will be persisted, one of which will remain immutable (account_auth) because historical versions will be persisted over time to support transaction queries.

First, a lexical change: In systemaccounting, there aren’t “users”, but “**accounts**”.

Secondly, the object currently passed by the client to the new endpoint during account creation must be divided into 2 object ‘kinds’ (https://cloud.google.com/datastore/docs/concepts/entities#ancestor_paths) by the time it reaches the Datastore where they will have an ancestor/child relationship defined as an ‘entity group’ (“When you create an entity, you can optionally designate another entity as its parent; the new entity is a child of the parent entity..., https://cloud.google.com/datastore/docs/concepts/entities#properties_and_value_types).”

The reason for separation is that profile data for an account will change over time and historical versions will remain in storage to support transaction queries. In contrast, historical versions of the account & password properties will not be persisted.

The first object, or root of this entity group is of the ‘account_auth’ kind:

account (key\* see Requirement 3 below)
password

The second object, or child of this entity group is of the ‘account_profile’ kind:

first_name
middle_name
last_name
date_of_birth
email_address
street_number
street_name
unit_number
floor_number
city
county
district
state
region
province
territory
postal_code
country
user_home_latlng
telephone_country_code
telephone_area_code
telephone_number
occupation
industry
created_time

Requirement 1: References to ‘user’ within properties & resources are changed to ‘account’ (in web client, too).

Requirement 2: Current object is split into two ‘kinds in the Datastore’: i) account_auth, ii) account_profile.

Requirement 3: Currently, each record is assigned a random numeric ID by the Datastore per https://cloud.google.com/datastore/docs/concepts/entities#ancestor_paths. Instead, assign the value of the account property to be the ‘key name’ for all account_auth entities (in other words, the username will be the key; not some number generated by the Datastore). The account_profile entities will receive a numeric ID.

Requirement 4: Entities of an account_profile kind are always designated as children of entities of account_auth kind.

**Comment by ghost** [comment]
please see PR #42

**Comment by mxfactorial** [comment]
Closed by https://github.com/systemaccounting/mxfactorial/pull/42
