### ISSUE TITLE
Retarget endpoints from Datastore to Firebase to improve endpoint reliability

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial#43]
Retarget endpoints currently serviced by the [App Engine flexible environment](https://cloud.google.com/appengine/docs/flexible/nodejs/runtime)'s Datastore to [Firebase](https://firebase.google.com/docs/server/setup)'s real-time database for the aim of improving their reliability (API instability first observed [in a comment](https://github.com/systemaccounting/mxfactorial/pull/27#issuecomment-226969527) on pull request #27).

Related documentation: [Data Model](https://github.com/systemaccounting/mxfactorial/wiki/Data-Model)

Requirements:
a. Account object is POSTed to Firebase db instead of Datastore
a. Transaction object is POSTed to Firebase db instead of Datastore

**Comment by mxfactorial** [comment]
If retargeting the account & transact endpoints to the Firebase db does not remedy i) the API instability as reported by @elvongray, and ii) the missing db values, then the source of this issue is likely the application layer. The documentation for this new flexible environment states, "This is a Beta release of the App Engine flexible environment."
Will deploy [application layer on Firebase](https://firebase.google.com/docs/hosting/) next to test if instability issues are resolved. If so, the project will proceed with development.

**Comment by mxfactorial** [comment]
@hotay , since transaction data has a dependency on account+profile data,  the "custom authentication" method on https://firebase.google.com/docs/auth/server/ will preserve this dependency while enabling access to other Firebase services per, "This identity will then be used when accessing other Firebase services, such as the Firebase Realtime Database and Firebase Storage."

**Comment by mxfactorial** [comment]
Added Firebase configuration files to master.
The app was deployed to new https://mxfactorial.firebaseapp.com production environment.

**Comment by hotay** [comment]
@mxfactorial https://firebase.google.com/docs/auth/server/ this actually handle access on our own server instead of authenticating to firebase service and other services. To grant access to those google's services we must use googleapis auth which I have included on PR #45

**Comment by mxfactorial** [comment]
Closed by https://github.com/systemaccounting/mxfactorial/pull/45

**Comment by mxfactorial** [comment]
@hotay, "handle access on our own server instead of authenticating to firebase service and other services"

Not referring to server accessing Firebase services, the "while enabling access to other Firebase services" comment was referring to user-level access to Firebase features such as the event system, etc.
