### ISSUE TITLE
Seperation of private and public routes

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial#64]
Currently we have no protection against private routes. Direct access to `Auth` required paths should be redirected to a public path (e.g `/login`).

------
#### Steps
1- Do not login or register on `/` page
2- Navigate `/account`

#### Expected
Browser redirect to landing screen

------

#### Steps
1- Login with valid credentials
2- Manually edit url `/not-a-valid-route`

#### Expected
Browser navigates to `404` route.

> 404 route should be created.

------

#### Steps

1- Login with valid credentials
2- See user will be loaded on `/accounts`
3- Navigate `/requests` screen
4- Click home link

#### Expected

Loading user should not be performed again.

---
@enesTufekci Others from draft:

**Navigating to requestsScreen without auth redirects to landingScreen**

**Steps**

1. Do NOT add credentials on /
2. Navigate browser to /requests

**Expected**
Browser redirects to `/auth`

---

**Navigating to historyScreen without auth redirects to landingScreen**

**Steps**
1. Do NOT add credentials on /
2. Navigate browser to /history

**Expected**
Browser redirects to `/auth`

---

**landingScreen**

**Steps**
1. Navigate to /

**Expected**
browser redirects `/auth` and landingScreen displays

---

**termsOfUseScreenOne**

**Steps**
1. Navigate to `/auth`
2. Select createAccountButton

**Expected**
redirects to `/auth/create-account` and termsOfUseScreenOne displays

---

**requestScreen**

**Steps**
1. Navigate to `/` ( automatically redirects to `/auth`)
2. Sign in
3. Select menuIcon
4. Select mainNavRequestButton

**Expected**
Browser navigate to `/requests` and displays requestScreen

---

**Implementation Details from** @enesTufekci 

1. Reduce main route count to 2: private, public
2. Create sub routes for main routes
3. Public Routes: `/auth`, `/auth/create-account`

Private Routes: `/account`, `/requests`, `/history`

Fix route paths
Public -> `/auth`
LandingScreen -> `/auth`
CreateAccount -> `/auth/create-account`

-------

Private -> `/account`
HomeScreen -> `/account`
RequestScreen -> `/requests`

Create a user context (`Context Api`) to cache authenticated user data which will feed private routes with user data.

Create a higher order component to bind the context to component.

**Comment by nstfkc** [comment]
Estimation: 5h + 1h?

**Comment by mxfactorial** [comment]
Approved. Please branch from and pr to `develop`

**Comment by nstfkc** [comment]
@mxfactorial Its ready to merge

current code coverage;

File                                       |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-------------------------------------------|----------|----------|----------|----------|-------------------|
All files                                  |    99.43 |      100 |    98.73 |      100 |                   |

**Comment by mxfactorial** [comment]
Closed by https://github.com/systemaccounting/mxfactorial/pull/65 _Private routes_
