### ISSUE TITLE
Cursor position locked in all but last transaction inputs

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial#67]
**Branch**: `private-routes`
**Client**: Chrome Version 68.0.3440.106 (Official Build) (64-bit)
**OS**: Mac OS 10.12.6 (16G1408)

**Steps**
1. Navigate to / to display landingScreen.
2. Sign In to display homeScreen.
3. Select addItemButton 3 times to display 3 empty input groups.
4. Insert cursor into first `input[name="transaction-add-name"]`.
5. Type `bread`.

**Observed**: Cursor position locked.

**Expected**: `bread` displays.

**Note**: Changing step 4 to "Insert cursor into **second** `input....`" produces same result. Cursor only moves in last input group. Please review "draft transaction" code. After fixing, please add `test('empty transaction inputs in multiple groups receive values',...` in e2e.

**Comment by nstfkc** [comment]
Fixed with https://github.com/systemaccounting/mxfactorial/pull/65/commits/e9497621a06052791218a71eac13d19205c550d2

**Comment by nstfkc** [comment]
e2e tests will be added on next commits.
Added -> https://github.com/systemaccounting/mxfactorial/pull/65/commits/0c3ed655a62e53b248438416ec231fdc702b0c7e

**Comment by mxfactorial** [comment]
Closed by https://github.com/systemaccounting/mxfactorial/pull/65 _Private routes_
