### ISSUE TITLE
requestDetailScreen

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial#68]
**References**

1. [transaction model](https://github.com/systemaccounting/mxfactorial/blob/cec04261f6e3e47356b2f0338f851bd71e2f59bc/graphql-faas/src/graphql/resolvers/Transaction.js#L85-L110)
2. [2,3,4 in wireframe](https://docs.google.com/drawings/d/1cF2Ai_lmOaXXI8Z2hso7tbWoNouYNgJ9eFCQES0rPcU/edit?usp=sharing)

---

**camelCase `data-id` values copied from requirements**

1. Set `data-id` to camelCase values from requirements.

**Expected**
End to end tests select on `data-id` values copied from requirements (reduces work fixing tests when UI improvements added later).

---

**requestDetailScreen**

1. Sign in to display homeScreen.
2. Select navigation button to display mobile nav menu.
3. Select "Requests" button on mobile nav menu to display requestScreen.
4. Select requestItemIndicator on requestScreen.

**Expected**

1. requestDetailScreen displays:
2. backButton
3. "Request" screen title copy
4. emailCopyButton
5. requestingAccountIndicator (!currentAccount)
6. sumTransactionItemIndicator ([price x quantity, ....].reduce())
7. requestTimeIndicator with "Time of request `{Day, Month Date, Year @ Time}`" copy
8. expirationTimeIndicator with "Time of expiration `{Day, Month Date, Year @ Time}`" copy
9. transactButton
10. rejectButton
11. transactionItemIndicator(s) with "quantity x price name" copy
12. "Transaction ID" copy
13. transactionIdIndicator
14. "Rule Instance IDs" copy
15. ruleInstanceIdsIndicator
16. "Pre-transaction balance"
17. preTransactionBalanceIndicator

---

**passwordApproveTransactionPopUp**

1. Select transactButton on requestDetailScreen.

**Expected**

1. passwordApproveTransactionPopUp displays:
2. sumTransactionItemIndicator
3. "Enter password" copy
4. passwordInputField
5. cancelButton
6. okButton

---

**Dismiss passwordApproveTransactionPopUp**

1. Select transactButton on requestDetailScreen to display passwordApproveTransactionPopUp.
2. Select cancelButton on passwordApproveTransactionPopUp.

**Expected**

1. passwordApproveTransactionPopUp dismissed.
2. requestDetailScreen displays.

---

**transactionSuccessPopup**

1. Add TRUE password to passwordInputField on passwordApproveTransactionPopUp.
2. Select okButton on passwordApproveTransactionPopUp.

**Expected**

1. transactionSuccessPopup displays:
2. newButton
3. okButton

*Note: transactionSuccessPopup will display above historyScreen in **future** requirement.

---

**Invalid styling and Incorrect Password copy on passwordApproveTransactionPopUp**

1. Add FALSE password to passwordInputField on passwordApproveTransactionPopUp.
2. Select okButton on passwordApproveTransactionPopUp.

**Expected**

1. passwordInputField displays empty with [:invalid](https://developer.mozilla.org/en-US/docs/Web/CSS/:invalid) styling.
2. Red "Incorrect Password" appears inside :invalid styled passwordInputField.

---

**Remove Incorrect Password copy and invalid styling from passwordInputField**

1. Add FALSE password to passwordInputField on passwordApproveTransactionPopUp.
2. Select okButton on passwordApproveTransactionPopUp.
3. Select invalid styled passwordInputField to attempt another password.

**Expected**

1. Initial passwordInputField styling displays.

---

**homeScreen from transactionSuccessPopup**

1. Add password to passwordInputField on passwordApproveTransactionPopUp.
2. Select okButton on passwordApproveTransactionPopUp to display transactionSuccessPopup.
3. Select newButton on transactionSuccessPopup.

**Expected**

1. homeScreen displays.

**Comment by nstfkc** [comment]
Estimation: 12h

**Comment by mxfactorial** [comment]
**Unresponsive background when any popup displays**

1. Select button to display popup.
2. Select area not covered by popup.

**Expected**

1. Background and popup unchanged.

**Comment by mxfactorial** [comment]
Approved. Please branch from `develop`.

**Comment by mxfactorial** [comment]
closed by:
https://github.com/systemaccounting/mxfactorial/pull/70
https://github.com/systemaccounting/mxfactorial/pull/72
