### ISSUE TITLE
historyScreen and historyDetailScreen

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial#69]
**References**:

1. [transaction model](https://github.com/systemaccounting/mxfactorial/blob/cec04261f6e3e47356b2f0338f851bd71e2f59bc/graphql-faas/src/graphql/resolvers/Transaction.js#L85-L110)
2. [1,2 in wireframe](https://docs.google.com/drawings/d/1W4KTDjrqXGz7Xvv56529XBKnOoDdwBZzqUyHPuYQGbE/edit?usp=sharing)

---

**camelCase `data-id` values copied from requirements**

1. Set `data-id` to camelCase values from requirements.

**Expected**

1. End to end tests select on `data-id` values copied from requirements (reduces work fixing tests when UI improvements added later).

---

**historyScreen**

1. Sign in to display homeScreen.
2. Select navigation button to display mobile nav menu.
3. Select "History" button on mobile nav menu.

**Expected**

1. historyScreen displays:
2. currentAccountBalanceIndicator
3. historyItemIndicator (transaction where credit_time && debit_time)
4. time of transaction in historyItemIndicator
5. transaction partner in historyItemIndicator
6. amount and direction of transaction (positive or negative)

---

**historyDetailScreen**

1.  Select historyItemIndicator on historyScreen.

**Expected**

1. historyDetailScreen displays:
2. backButton
3. "Detail" copy
4. emailCopyButton
5. contraAccountIndicator
6. sumTransactionItemValueIndicator ([price x quantity, ....].reduce())
7. transactionTimeIndicator with `{Day, Month Date, Year @ Time}` copy
8. transactionItemIndicator(s) with "quantity x price name" copy
9. "Transaction ID" copy
10. transactionIdIndicator
11. "Rule Instance IDs" copy
12. ruleInstanceIdsIndicator
13. "Pre-transaction balance" copy
14. preTransactionBalanceIndicator
15. "Post-transaction balance" copy
16. postTransactionBalanceIndicator
17. disputeTransactionButton

---

**historyScreen navigation from historyDetailScreen**

1. Select backButton on historyDetailScreen.

**Expected**

1. historyScreen displays.

---

**homeScreen navigation from historyScreen**

1. Select backButton on historyScreen.

**Expected**

1. homeScreen displays.

---

**homeIcon**

1. Select homeIcon from any screen.

**Expected**

1. homeScreen displays. 

---

**Estimations will include unit and e2e test coverage of requirements. New screens will include an e2e inventory test ([example](https://github.com/systemaccounting/mxfactorial/blob/cec04261f6e3e47356b2f0338f851bd71e2f59bc/react/e2e/private/homeScreen/homeScreenInventory.test.js)).*

**Comment by oozywaters** [comment]
Estimate: 16h

**Comment by mxfactorial** [comment]
Please itemize tasks summing to 16 hours. Otherwise, 10 hours to add a near duplicate screen with tests preferred.

**Comment by oozywaters** [comment]
New estimation: 10h

**Comment by mxfactorial** [comment]
Approved.
Please `git checkout -b history` from `develop` and create pull request after first commit.

**Comment by mxfactorial** [comment]
Closed by https://github.com/systemaccounting/mxfactorial/pull/73
