### ISSUE TITLE
Add CSS to RequestDetailScreen

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial#71]
![screen shot 2018-10-27 at 5 07 15 pm](https://user-images.githubusercontent.com/12200465/47610545-93dd0b80-da0c-11e8-8c5d-983fd61182b0.png)

**Comment by oozywaters** [comment]
Estimate: 2h

**Comment by mxfactorial** [comment]
Approved

**Comment by mxfactorial** [comment]
closed by https://github.com/systemaccounting/mxfactorial/pull/72
