### ISSUE TITLE
Print version and build details

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial#74]
### general change

**print version on landingScreen**

1. navigate to `/` 

**expected**
similarly styled `<IntroStyled>{process.env.REACT_APP_VERSION}</IntroStyled>` displayed at bottom of LandingScreen.js (increase top margin)

----

### changes for acceptance builds only

**expose build and version to react app**

1. Add to `.env.development.local`:
```
REACT_APP_TEST_ENV=dev
REACT_APP_TEST_VERSION=$npm_package_version
REACT_APP_TEST_BRANCH=$(git branch | grep \* | cut -d ' ' -f2)
REACT_APP_TEST_DEVELOPER=
REACT_APP_TEST_PR_NUMBER=
REACT_APP_TEST_BUILD_NUMBER=
REACT_APP_PR_URL=
REACT_APP_BUILD_URL=
```

**expected**
variables accessible to react app

**note**: 
last 2 exclude `TEST` substring

---

**conditionally display build and version values in main nav menu**

1. add `if (REACT_APP_HOST_ENV)...` condition to display test build values
2. select main nav hamburger menu button

**expected**
1. only nonempty REACT_APP_TEST_* values added as items to bottom of main nav menu; set alternative background coloring for items, and list scrollable if too long
2. if nonempty, display `PR ${process.env.REACT_APP_TEST_PR_NUMBER}` linked to `REACT_APP_PR_URL` in new window
3. if nonempty, display `Build ${process.env.REACT_APP_TEST_BUILD_NUMBER}` linked to `REACT_APP_BUILD_URL` in new window

**note**: 
ci will populate from [built-in vars](https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables)

----

**general notes**: 
1. only `version displays on landing screen` and `test menu items NOT displayed` e2e test required
2. unit tests required
3. remove REACT_APP_TEST_ENV from `.env.development.local` after finishing development since it will break main nav e2e tests. intended only for CI build and deploy of commits tagged for acceptance testing

**Comment by oozywaters** [comment]
1. Display env variables on landing screen and in main nav menu (tests included) - 2h
2. Fix scrolling in nav menu modal for correct display of scrollable env items list - 1h

Total estimate: 3h

**Comment by mxfactorial** [comment]
Vyacheslav, please propose any tech debt requirements you wish to prioritize to bundle in this task with estimations.

**Comment by oozywaters** [comment]
I’d like to refactor e2e tests in a way that a single puppeteer instance is used throughout all tests. I think it will reduce testing time and will help to avoid `beforeAll()` and `afterAll()` duplications in every test suite.

I suggest we integrate jest-puppeteer library https://github.com/smooth-code/jest-puppeteer

Estimate: 3h

**Comment by oozywaters** [comment]
Total estimate: 6h

**Comment by mxfactorial** [comment]
Approved, please branch from develop.

**Comment by mxfactorial** [comment]
Closed by https://github.com/systemaccounting/mxfactorial/pull/75
