### ISSUE TITLE
Add mock GraphQL rules query endpoint

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial#76]
1. add rules query to [graphql-faas](https://github.com/systemaccounting/mxfactorial/tree/master/graphql-faas/src/graphql) accepting [transactions](https://github.com/systemaccounting/mxfactorial/blob/82e11a6c074847e9d104f1d25c5fd58e5f2fe9cd/react/src/screens/HomeScreen/README.md#transaction-model) array type
2. in new [resolvers/rules.js](https://github.com/systemaccounting/mxfactorial/tree/master/graphql-faas/src/graphql/resolvers), add resolver mocking call to new /rules service returning transaction modification function:
temporarily hardcode in resolver an updated Transaction Rule Script ([trs](https://www.google.com/search?q=terse)) that adds a 9% sales tax transaction item to any array (see old [addNinePercentPerItemCaliforniaStateSalesTax.js](https://gist.github.com/mxfactorial/2c688ca79946f1305589e017c2e315d9) example containing deprecated key names and payload structure; refer to [transactions array of bread, milk and honey](https://github.com/systemaccounting/mxfactorial/blob/82e11a6c074847e9d104f1d25c5fd58e5f2fe9cd/react/src/screens/HomeScreen/README.md#transaction-model) as current requirement). new mock sales tax trs will return a new array with a sales tax transaction object added for any user instead of matching on single account, e.g. `DannysMarket` in old version
3. in react client, add milk to item input field
4. [removing cursor](https://developer.mozilla.org/en-US/docs/Web/Events/blur) from item input field sends transaction array to /rules query endpoint
5. 0 additional transaction objects returned
6. add 5.00 to milk price input field
7. removing cursor from price input field sends transaction array to /rules query endpoint
8. with client assuming 1 quantity default, 1 additional transaction object returned from /rules containing "[9% state sales tax](https://gist.github.com/mxfactorial/2c688ca79946f1305589e017c2e315d9#file-addninepercentperitemcaliforniastatesalestax-js-L37)" and price = [1 quantity x 1.09 x 5.00 milk price](https://gist.github.com/mxfactorial/2c688ca79946f1305589e017c2e315d9#file-addninepercentperitemcaliforniastatesalestax-js-L25)
9. new sales tax object has `rule_instance_id` populated with mock value
10. `if (rule_instance_id)`, new sales tax object displays below all user-generated transaction items in client
11. `if (rule_instance_id)`, new sales tax object displays WITHOUT transactionClear button (rule-generated objects not removable)
12. add 3 to milk quantity input field
13. removing cursor from quantity input field sends transaction array to /rules query endpoint
14. updated transaction object returned from /rules containing 3 x 1.09 x price sales tax
15. add bread item with price and quantity
16. sales tax transaction object increments by quantity x 1.09 x price
---
i. exclude test coverage from estimation this task; new test coverage task issued after to avoid excessive changes during feature r&d
ii. send GET /rules (graphql) onblur from all transaction input fields except where `rule_instance_id` not populated; user-generated

**Comment by oozywaters** [comment]
Estimate: 6h

**Comment by mxfactorial** [comment]
Approved

**Comment by mxfactorial** [comment]
Please issue incremental estimation for refactoring tests to assert values increased by rule-generated objects.

**Comment by oozywaters** [comment]
Additional estimate: 2h

**Comment by mxfactorial** [comment]
Approved

**Comment by mxfactorial** [comment]
2h estimation issued in https://github.com/systemaccounting/mxfactorial/pull/77#issuecomment-451737790 approved.

**Comment by mxfactorial** [comment]
closed by https://github.com/systemaccounting/mxfactorial/pull/77
