### ISSUE TITLE
add terraform/modules/api-gateway

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial#79]
1. add terraform/modules/api-gateway
2. add main.tf, outputs.tf and variables.tf to terraform/modules/api-gateway
3. duplicate terraform/workspaces/api-gateway.tf into terraform/modules/api-gateway/main.tf
4. replace contents of terraform/workspaces/api-gateway.tf with module referencing terraform/modules/api-gateway/main.tf as source
5. add cors to new api-gateway module
6. `terraform apply` to dev first, then prod when bugs = 0

**Comment by oozywaters** [comment]
Estimate: 2h

**Comment by mxfactorial** [comment]
approved, please branch from develop.

**Comment by mxfactorial** [comment]
closed by https://github.com/systemaccounting/mxfactorial/pull/81
applied in prod
