### ISSUE TITLE
sumTransactionItemValueDisplayCell displays .toFixed(3)

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial#87]
**client**: 0.1.6
**server**: 1.0.0
**browser**: Version 71.0.3578.98 (Official Build) (64-bit)

1. add account with active 9.5% sales tax rule to recipientAccountInputField
2. add milk, 2.00, 3
3. add honey 4, 4
4. add pasta 5, 5

**expected**
sumTransactionItemValueDisplayCell displays 51.230, where value[.toFixed(3)
](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed)
**observed**
![screen shot 2019-01-30 at 8 47 50 pm](https://user-images.githubusercontent.com/12200465/52031667-85eacb00-24d2-11e9-947a-50c08d09b74a.png)

**Comment by oozywaters** [comment]
Estimate: 0.5h

**Comment by mxfactorial** [comment]
Approved. Branch from develop please.

**Comment by mxfactorial** [comment]
closed by https://github.com/systemaccounting/mxfactorial/pull/89
