### ISSUE TITLE
INSERT rules-tested transaction items

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial#91]
**/transact service receives transactions items**

1. add milk x 2 x 2, bread x 3 x 3, honey x 4 x 4 items
1. select request button
1. POST mutation

**expected**
1. /transact service receives milk, bread, honey and tax transactions items

---

**/transact service tests transactions items against /rules**

1. /transact service receives milk, bread, honey and tax items

**expected**
1. /transact service assigns recieved items as itemsUnderTestArray, then logs
1. /transact service POST /rules itemsUnderTestArray
1. /transact service assigns POST /rules response to itemsStandardArray, then logs
1. /transact service tests itemsUnderTestArray for [equality](https://lodash.com/docs/4.17.5#isEqual) with itemsStandardArray (use [sortBy](https://lodash.com/docs/4.17.5#sortBy) first if using _.)

---

**INSERT into transactions table**

1. return `true` from /transact service testing equality of itemsUnderTestArray with itemsStandardArray

**expected**
1. /transact service logs EQUALITY message with identical item arrays
1. /transact service INSERTs itemsUnderTestArray into transactions table

---

**unequal transaction items**

1. send array missing a rules-required item to /transact
1. return `false` from /transact service testing equality of itemsUnderTestArray with itemsStandardArray

**expected**
1. /transact service logs UNEQUAL message with unidentical item arrays
1. /transact service returns `required items missing` error to client
1. /transact service does **NOT** INSERT itemsUnderTestArray into transactions table
---

**Estimations will include unit and e2e test coverage of requirements. New screens will include an e2e inventory test ([example](https://github.com/systemaccounting/mxfactorial/blob/cec04261f6e3e47356b2f0338f851bd71e2f59bc/react/e2e/private/homeScreen/homeScreenInventory.test.js)).*

**Comment by oozywaters** [comment]
#### Client-side:
1. Add mutation query and POST transactions to the api on Request button click (2h)

#### Server side:
1. Add resolver to the graphql service sending data to transact service (2h)
2. Transaction service posts data to rules service to compare data sets (2h)
3. Store data in mysql db if sets are equal (2h)
4. Return and log error if sets are unequal (1h)

**Total estimate: 9h**

**Comment by oozywaters** [comment]
Do we need tests for backend-related stuff?

**Comment by mxfactorial** [comment]
Yes, backend tests required, please include in estimation.

> 1. Add resolver to the graphql service sending data to transact service (2h)

[resolver added](https://github.com/systemaccounting/mxfactorial/blob/develop/services/graphql-faas/src/graphql/resolvers/Transaction.js#L14) when setting up this task and passes [integration testing](https://circleci.com/gh/systemaccounting/mxfactorial/1369).

> 2. Transaction service posts data to rules service to compare data sets (2h)

please continue use of [invoke()](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#invoke-property) for intra-service communication. 
2 paths exists for each service: i. public path routed through api gateway, ii. private, shortcut path remaining inside service layer. 
ignoring auth for now, clients will send requests to api gateway which will call the same method as intra-service invoke(). current priority is writing services so they are conveniently ported to container networking. design of distinguishing public vs. private traffic will evolve. 

please update estimates

EDIT: adjusting line reference after https://github.com/systemaccounting/mxfactorial/commit/669f159ca6a8498074a2779ccc95fdb0d8dd4273

**Comment by oozywaters** [comment]
Updated estimation:

#### Client-side:
1. Add mutation query and POST transactions to the api on Request button click (2h)
2. Add e2e and unit testing (1h)

#### Server side:
1. Transaction service posts data to rules service to compare data sets (2h)
2. Rules service returns list of transactions with rules applied (2h)
3. Store data in mysql db if sets are equal (2h)
4. Return and log error if sets are unequal (1h)
5. Change unit and integration tests of transact service according to new requirements (3h)
6. Unit and integration testing of rules service (2h)

**Total: 15h**

**Comment by mxfactorial** [comment]
Let us begin negotiating due dates. Not intended to cause you misery, but schedule development. Accept a 3/8 due date?

**Comment by oozywaters** [comment]
Agreed.

**Comment by mxfactorial** [comment]
Approved, from develop please.

**Comment by mxfactorial** [comment]
relieving 3/8 due date commitment. will resume after service networking added

**Comment by oozywaters** [comment]
/transact service tests transactions items against /rules
4. /transact service tests itemsUnderTestArray for equality with itemsStandardArray
[https://github.com/systemaccounting/mxfactorial/blob/insert-transactions/services/transact-faas/tests/testRules/testRules.test.js#L31-L37](url)

INSERT into transactions table
2. /transact service INSERTs itemsUnderTestArray into transactions table
[https://github.com/systemaccounting/mxfactorial/blob/insert-transactions/services/transact-faas/tests/insertTransactions/insertTransactions.test.js#L34-L37](url)

unequal transaction items
2. /transact service returns required items missing error to client
3. /transact service does NOT INSERT itemsUnderTestArray into transactions table
[https://github.com/systemaccounting/mxfactorial/blob/insert-transactions/services/transact-faas/tests/insertTransactions/insertTransactions.test.js#L39-L44](url)

**Comment by mxfactorial** [comment]
closed by https://github.com/systemaccounting/mxfactorial/pull/92
