### ISSUE TITLE
/transact adds debitor_approval_time and creditor_approval_time instead of client

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial#93]
**goal**: */transact **always** ignores `debitor_approval_time` and `creditor_approval_time` values received from clients. only /transact will set timestamp values in db after auth. auth will come later.*

current task: remove all client code assigning `debitor_approval_time` and `creditor_approval_time` values. client continues to support `debitor_approval_time` and `creditor_approval_time` properties, and can even resend values initially assigned by /transact, but /transact always ignores client versions of `debitor_approval_time` and `creditor_approval_time` values

---

react test

1. create transaction from client
1. POST /transact

**expected**
client POSTs [all transaction item values](https://github.com/systemaccounting/mxfactorial/blob/ce32f5fccb0f317439f8224e114458f158d3825c/services/graphql-faas/src/graphql/types/Transaction.js#L116-L141) **except** values for `debitor_approval_time` and `creditor_approval_time`

---

/transact mock test

1. /transact receives items from client
1. /transact tests items against rules
1. /transact adds `debitor_approval_time` and `creditor_approval_time` values to all items

**expected**
transactions stored in db with mysql datetime value

---

/transact mock test

1. /transact receives items from client with `debitor_approval_time` and `creditor_approval_time` values
1. /transact tests items against rules
1. /transact adds `debitor_approval_time` and `creditor_approval_time` values to all items

**expected**
transactions stored in db with mysql datetime values from Step 3

---

**Estimations will include unit and e2e test coverage of requirements. New screens will include an e2e inventory test ([example](https://github.com/systemaccounting/mxfactorial/blob/cec04261f6e3e47356b2f0338f851bd71e2f59bc/react/e2e/private/homeScreen/homeScreenInventory.test.js)).*

**Comment by oozywaters** [comment]
1. Exclude `debitor_approval_time` and `creditor_approval_time` from `createTransaction` request + unit test - 1h
2. Set actual `debitor_approval_time` and `creditor_approval_time` in /transact service + unit test - 1h
3. Make sure /transact ignores `debitor_approval_time` and `creditor_approval_time` received from client and set correct `debitor_approval_time` and `creditor_approval_time` + unit test - 1h

**Total estimate: 3h**

**Comment by mxfactorial** [comment]
Approved, from develop please

**Comment by oozywaters** [comment]
Are `debitor`, `creditor`, `author` [fields](https://github.com/systemaccounting/mxfactorial/blob/ce32f5fccb0f317439f8224e114458f158d3825c/services/graphql-faas/src/graphql/types/Transaction.js#L116-L141) required when submitting transaction from client?
If so, need to increase estimate to assign correct values to transaction items (and re-assign them when debit/credit buttons toggled): **+2h**

**Comment by mxfactorial** [comment]
> required when submitting transaction from client?

depends on type. **all** transactions begin as either of the following _request_ types:

[bid](https://en.wikipedia.org/wiki/Bid_price): `!creditor_approval_time && debitor_approval_time`
[ask](https://en.wikipedia.org/wiki/Ask_price): `creditor_approval_time && !debitor_approval_time`

then, request achieves [equilibrium](https://en.wiktionary.org/wiki/equilibrium_price) when the missing `*_approval_time` added.

`debitor`, `creditor` and `author` required for bid or ask, but not for equilibrium type because these values fetched with ids of previously created records

+2 hours approved

**Comment by mxfactorial** [comment]
closed by https://github.com/systemaccounting/mxfactorial/pull/95
