### ISSUE TITLE
storing credit and debit requests

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial#94]
1. sign in to set current authenticated user = `author`
1. create credit request on client, `author` = `creditor`
1. client tests transactions against /rules
1. /rules returns tested transactions
1. client sends /rules-tested transactions to /transact
1. /transact tests transactions against /rules
1. /transact stores /rules-tested transactions received from client in db

**expected**
transactions added with `creditor_approval_time` and NOT `debitor_approval_time`

---

1. sign in to set current authenticated user = `author`
1. create debit request on client, `author` = `debitor`
1. client tests transactions against /rules
1. /rules returns tested transactions
1. client sends /rules-tested transactions to /transact
1. /transact tests items against /rules
1. /transact stores /rules-tested transactions received from client in db

**expected**
transactions added with `debtor_approval_time` and NOT `creditor_approval_time`

---

**Estimations will include unit and e2e test coverage of requirements. New screens will include an e2e inventory test ([example](https://github.com/systemaccounting/mxfactorial/blob/cec04261f6e3e47356b2f0338f851bd71e2f59bc/react/e2e/private/homeScreen/homeScreenInventory.test.js)).*

**Comment by oozywaters** [comment]
Estimation including tests: 2h

**Comment by mxfactorial** [comment]
Approved

**Comment by mxfactorial** [comment]
please add estimation for reverting "...and can even resend values initially assigned by /transact" by removing `debtor_approval_time` and `creditor_approval_time` from https://github.com/systemaccounting/mxfactorial/blob/c9229653a87875e6fba33f7b365bd72badbeffbb/services/graphql-faas/src/graphql/types/Transaction.js
while wishing to minimize request errors for third-party client developers, avoiding confusion for server devs is priority, e.g. _declared in api schema but not used anywhere?_

**Comment by oozywaters** [comment]
`debitor_approval_time` and `creditor_approval_time` are not sent by client now, so we can freely remove those fields from schema

**Comment by mxfactorial** [comment]
+1 hour per https://github.com/systemaccounting/mxfactorial/pull/96#issuecomment-487309778

**Comment by mxfactorial** [comment]
closed by https://github.com/systemaccounting/mxfactorial/pull/96
