### ISSUE TITLE
display stored debit and credit requests on client

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial#98]
1. sign in to display homeScreen
1. debit and credit requests matching authenticated account fetched from `graphql`
1. graphql resolves `measure-faas`

**expected**  
`measure-faas` returns to `gaphql`:
```sql
(select *
FROM transactions
WHERE creditor='Person1' OR debitor='Person1'
AND (creditor_approval_time IS NULL OR debitor_approval_time IS NULL)
ORDER BY id desc limit 20) ORDER BY id;
```

* *note: 20 record limit avoids table scans during development. add more sophisticated querying for request history later.*

---

1. sign in to display homeScreen
1. debit and credit requests matching authenticated account fetched from `graphql`

**expected**  
1. graphql returns 20 most recent debit and credit requests matching authenticated account

---

1. sign in to display homeScreen
1. debit and credit requests matching authenticated account fetched from `graphql`

**expected**  
1. 20 most recent debit and credit requests matching authenticated account stored in client state

---

1. sign in to display homeScreen
1. select mainNavButton to display mainNavMenu
1. select mainNavRequestButton

**expected**  
1. debit and credit requests matching authenticated account fetched from `graphql` (requests fetched on display of homeScreen && requestScreen)
1. [requestScreen](https://docs.google.com/drawings/d/1cF2Ai_lmOaXXI8Z2hso7tbWoNouYNgJ9eFCQES0rPcU/edit?usp=sharing) displays 20 most recent debit and credit requests matching authenticated account (order by approval timestamp)

---

1. navigate `Person1` to requestScreen
1. `Person2` sends `Person1` debit request
1. `Person1` refreshes requestScreen

**expected**  
1. debit request from step 2 displays on `Person1`'s request screen

---

**Estimations will include unit and e2e test coverage of requirements. New screens will include an e2e inventory test ([example](https://github.com/systemaccounting/mxfactorial/blob/cec04261f6e3e47356b2f0338f851bd71e2f59bc/react/e2e/private/homeScreen/homeScreenInventory.test.js)).*

**Comment by oozywaters** [comment]
1. Add `measure-faas` resolver to graphql service - 1h
2. `measure-faas` selects authenticated user's 20 most recent transactions - 3h
3. Store transactions in client state - 2h
4. requestScreen displays requested transactions (+e2e tests) - 2h
5. Refresh requestScreen transactions list if debit/credit request is sent - 5h (need to research what is the most appropriate pubsub implementation in current environment, estimation may change later)

**Total: 13h**

**Comment by mxfactorial** [comment]
Approved, from develop please

**Comment by mxfactorial** [comment]
note new [measure-faas resolver](https://github.com/systemaccounting/mxfactorial/blob/master/services/graphql-faas/src/graphql/resolvers/Transaction.js#L26-L43) requires double parsing after integrating with go service

**Comment by mxfactorial** [comment]
closed by https://github.com/systemaccounting/mxfactorial/pull/101
