### ISSUE TITLE
add authentication to api

### ISSUE THREAD

**Issue by mxfactorial** [systemaccounting/mxfactorial#99]
1. add `COGNITO_USER_POOLS` type [authorizer](https://www.terraform.io/docs/providers/aws/r/api_gateway_authorizer.html) to [graphql api gateway](https://github.com/systemaccounting/mxfactorial/blob/3e1632d638baf41c14596f61abd209a523b1c262/terraform/modules/environment/graphql-api.tf)

**expected**  
`COGNITO_USER_POOLS` type authorizer available on graphql api gateway

---

1. sign into account on react client
1. pass [user pool token](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html) returned from cognito in POST /graphql/transactions [Authorization header](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-invoke-api-integrated-with-cognito-user-pool.html) (query)

**expected**  
/graphql responds with transactions

---

1. sign into account on react client
1. EXCLUDE [user pool token](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html) returned from cognito in POST /graphql/transactions [Authorization header](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-invoke-api-integrated-with-cognito-user-pool.html) (query)

**expected**  
/graphql responds "not authorized"

---

**Estimations will include unit and e2e test coverage of requirements. New screens will include an e2e inventory test ([example](https://github.com/systemaccounting/mxfactorial/blob/cec04261f6e3e47356b2f0338f851bd71e2f59bc/react/e2e/private/homeScreen/homeScreenInventory.test.js)).*

**Comment by oozywaters** [comment]
1. Add authorizer to graphql service, handle empty or wrong auth token with "not authorized" response [3h]
2. Pass auth token to apollo client requests [1h]
3. Tests [3h]

**Total estimate: 7h**

**Comment by mxfactorial** [comment]
Approved, from your current dev branch please

**Comment by mxfactorial** [comment]
closed by https://github.com/systemaccounting/mxfactorial/pull/104
